services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bits\IsoMasonryBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
